services:
  odoo_18web:
    image: odoo:18.0
    container_name: odoo18_web
    user: root
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    environment:
      - HOST=${HOST}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
    ports:
      - "8089:8069"
    volumes:
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons
      - ./log:/var/log/odoo
      - ./data:/var/lib/odoo
    depends_on:
      - odoo_18db
    networks:
      - odoo18

  odoo_18db:
    image: postgres:15
    container_name: odoo18_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - odoo18

networks:
  odoo18:
    driver: bridge
